### ISSUE TITLE
Generates wrong key

### ISSUE THREAD

**Issue by corpetty** [status-im/infra-utils#3]
The tool does not generate the correct key.

If I had to guess, it is generating the master key of the BIP44 standard key that we use in Status.

@cammellos could you take a look at the implementation to verify?

**Comment by jakubgs** [comment]
@corpetty is referring to https://github.com/status-im/infra-utils/tree/master/seed2key.

**Comment by gravityblast** [comment]
@corpetty @jakubgs what key is it supposed to generate?
From the code I see it prints the master key, not the BIP44 key, is that what we need?

**Comment by jakubgs** [comment]
What I wanted to achieve is get the key hex that I could use with [status-console-client](https://github.com/status-im/status-console-client):
```
 $ ./bin/status-term-client --help 2>&1 | grep -A1 keyhex
  -keyhex string
    	pass a private key in hex
```

**Comment by jakubgs** [comment]
Based on what I got from @adambabik:
https://github.com/status-im/status-go/blob/cfdeaa4b984900274d87f396c97480be2a09a9c9/vendor/github.com/ethereum/go-ethereum/accounts/keystore/key.go#L153-L164
I assumed that what I'm missing is something like this:
```go
	chatKey, err := masterKey.ChildForPurpose(extkeys.KeyPurposeChat, 0)
	if err != nil {
		fmt.Printf("cannot extract chat key from master key: %v\n", err)
		os.Exit(1)
	}
```
But I tried that and I'm still not getting the right key.

**Comment by jakubgs** [comment]
I did check the `Depth` attribute of my `masterKey` that I got from:
```go
masterKey, err := extkeys.NewMaster(mnemonic.MnemonicSeed(seedPhrase, ""))
```
and I'm getting `0`, so I assume that I'm dealing with a master key.
So either `ChildForPurpose()` method isn't returning what I want, or I'm not printing it right using:
```go
fmt.Printf("%#x\n", crypto.FromECDSA(chatKey.ToECDSA()))
```

**Comment by jakubgs** [comment]
@gravityblast can you help me out?

**Comment by gravityblast** [comment]
@jakubgs sure!
Yes that's the master key, here an example:

```
fmt.Printf("Master Private Key\n%#x\n", crypto.FromECDSA(masterKey.ToECDSA()))

bip44Key0, err := masterKey.BIP44Child(extkeys.CoinTypeETH, 0)
if err != nil {
	fmt.Printf("can not derive child key: %v\n", err)
	os.Exit(1)
}

fmt.Printf("Private Key derived at m/44'/60'/0'/0/0\n%#x\n", crypto.FromECDSA(bip44Key0.ToECDSA()))
```

The output will print the master private key and then the private key of the BIP44 key at index 0, which is the one we currently use in Status.

Which one do you need? Can you try with your mnemonic and see if the output is correct?

**Comment by jakubgs** [comment]
Okay, so that doesn't make sense to me considering the `status-go` code:
```go
func (k *ExtendedKey) ChildForPurpose(p KeyPurpose, i uint32) (*ExtendedKey, error) {
	switch p {
	case KeyPurposeWallet:
		return k.EthBIP44Child(i)
	case KeyPurposeChat:
		return k.EthEIP1581ChatChild(i)
	default:
		return nil, ErrInvalidKeyPurpose
	}KeyPurposeWallet
}
```
https://github.com/status-im/status-go/blob/023d2f4e7a10cd6ee9c9a59d5e2b8fdebe828fa6/extkeys/hdkey.go#L267-L276
And:
```go
func (k *ExtendedKey) BIP44Child(coinType, i uint32) (*ExtendedKey, error) {
	return k.EthBIP44Child(i)
}
```
https://github.com/status-im/status-go/blob/023d2f4e7a10cd6ee9c9a59d5e2b8fdebe828fa6/extkeys/hdkey.go#L282-L284

What you are saying is that the Status chat key is derived using `BIP44Child`, but the code clearly says that `BIP44Child` is used for `KeyPurposeWallet`, not `KeyPurposeChat`.

So either the meaning of `KeyPurposeWallet` and `KeyPurposeChat` must be flipped, or I'm having a brain aneurysm right now.

**Comment by jakubgs** [comment]
I just verified it, and it appears that `KeyPurposeWallet` is indeed the one that gives me the hex key that when used with `status-console-client` gives me my Status identity.

So can you please explain to me why the meanings are flipped?

**Comment by jakubgs** [comment]
@corpetty, can you verify that this fix works: https://github.com/status-im/infra-utils/commit/a686b447821eba62a2151a1237e0b0681163ca2a
It should.

**Comment by corpetty** [comment]
Works as intended.

**Comment by gravityblast** [comment]
> What you are saying is that the Status chat key is derived using BIP44Child, but the code clearly says that BIP44Child is used for KeyPurposeWallet, not KeyPurposeChat.

Where am I saying this?
In the current Status app (before multi-account), chat key and wallet key are the same, the BIP44 key.
The `KeyPurposeChat` will be the right derivation path when we will switch to decouple the 2 keys.

**Comment by gravityblast** [comment]
ah now I understand what you were saying! So you wanted the chat key, but the code is confusing because we are not actually using it yet.

**Comment by jakubgs** [comment]
Ah, that makes sense, so it's using the wording that will make sense once multi-account lands, but doesn't make sense now. Thanks for the explanation!
